## Default Elasticsearch configuration from Elasticsearch base image.
## https://github.com/elastic/elasticsearch/blob/master/distribution/docker/src/docker/config/elasticsearch.yml
#
cluster.name: ${ELASTIC_CLUSTER_NAME}
#node.name:    ${ELASTIC_NODE_NAME}
network.host: 0.0.0.0
# transport.host: 0.0.0.0

## Cluster Settings
# discovery.seed_hosts: ${ELASTIC_DISCOVERY_SEEDS}
# cluster.initial_master_nodes: ${ELASTIC_INIT_MASTER_NODE}

## License
# xpack.license.self_generated.type: basic

# Security
xpack.security.enabled: true

# kinana
xpack.security.enrollment.enabled: true

## - ssl
xpack.security.transport.ssl:
  enabled: true
  verification_mode: certificate
  key: certs/elasticsearch.key
  certificate: certs/elasticsearch.crt
  certificate_authorities: certs/ca.crt

## - http
xpack.security.http.ssl:
  enabled: true
  key: certs/elasticsearch.key
  certificate: certs/elasticsearch.crt
  certificate_authorities: certs/ca.crt
  client_authentication: optional

# Monitoring
xpack.monitoring.collection.enabled: true