---
## Default Kibana configuration from Kibana base image.
## https://github.com/elastic/kibana/blob/master/src/dev/build/tasks/os_packages/docker_generator/templates/kibana_yml.template.js
#
server.name: kibana
server.host: "0.0.0.0"
server.shutdownTimeout: 5s
i18n.locale: zh-CN
monitoring.ui.container.elasticsearch.enabled: true

# Elasticsearch Connection
elasticsearch.hosts: [ "${ELASTICSEARCH_HOST_PORT}" ]

## X-Pack security credentials
elasticsearch.serviceAccountToken: "请复制.env.kibana.token内『KIBANA_SERVICE_ACCOUNT_TOKEN=』后的token"
elasticsearch.ssl.certificateAuthorities: [ "/certs/ca.crt" ]